<div style="background: #2c3e50; 
            color: white; 
            padding: 20px; 
            border-radius: 8px;
            margin: 10px 0;">
    <h1 style="margin: 0; font-size: 24px;">
        Étape 1 : Importation des packages
    </h1>
</div>

In [1]:
import pandas as pd
from datetime import datetime
import json
from bs4 import BeautifulSoup
import re

<div style="background: #2c3e50; 
            color: white; 
            padding: 20px; 
            border-radius: 8px;
            margin: 10px 0;">
    <h1 style="margin: 0; font-size: 24px;">
        Étape 2 : Importation et exploration des données
    </h1>
</div>

In [2]:
df = pd.read_json("inputs/evenements-publics-openagenda.json")
pd.set_option('display.max_columns', None)
df.head()

,uid,slug,canonicalurl,title_fr,description_fr,longdescription_fr,conditions_fr,keywords_fr,image,imagecredits,thumbnail,originalimage,updatedat,daterange_fr,firstdate_begin,firstdate_end,lastdate_begin,lastdate_end,timings,accessibility,accessibility_label_fr,location_uid,location_coordinates,location_name,location_address,location_district,location_insee,location_postalcode,location_city,location_department,location_region,location_countrycode,location_image,location_imagecredits,location_phone,location_website,location_links,location_tags,location_description_fr,location_access_fr,attendancemode,onlineaccesslink,status,age_min,age_max,originagenda_title,originagenda_uid,contributor_email,contributor_contactnumber,contributor_contactname,contributor_contactposition,contributor_organization,category,country_fr,registration,links
0,8125443,comptines-et-chansons-a-la-bibliotheque-3042763,https://openagenda.com/bml/events/comptines-et...,Comptines et chansons à la bibliothèque,Comptines et chansons avec Jérôme et sa guitare,<p>Comptines et chansons avec Jérôme et sa gui...,Réservation indispensable,None,https://cdn.openagenda.com/main/a96636f225bf4c...,BmL-Ville de Lille,https://cdn.openagenda.com/main/a96636f225bf4c...,https://cdn.openagenda.com/main/a96636f225bf4c...,2025-01-15T13:25:12+00:00,"Samedi 29 mars, 10h15",2025-03-29T09:15:00+00:00,2025-03-29T10:30:00+00:00,2025-03-29T09:15:00+00:00,2025-03-29T10:30:00+00:00,"[{""begin"": ""2025-03-29T10:15:00+01:00"", ""end"":...",pi;ii,"[handicap psychique, handicap intellectuel]",32765922,"{'lon': 3.071976, 'lat': 50.619642999999996}",médiathèque de Moulins,8 allée de la Filature 59 000 Lille,Lille-Moulins,59350.0,59000.0,Lille,Nord,Hauts-de-France,FR,https://cdn.openagenda.com/main/location327659...,None,03 28 55 30 93,http://bm-lille.fr,http://@bibliotheques.lille,None,None,None,"{""id"": 1, ""label"": {""fr"": ""Sur place"", ""en"": ""...",None,"{""id"": 1, ""label"": {""fr"": ""Programm\u00e9"", ""e...",NaN,3.0,Bibliothèque municipale de Lille,13451012,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""phone"", ""value"": ""03 28 55 30 93""}]",None
1,11087187,auditions-grange-dimiere-absolution,https://openagenda.com/agenda-du-territoire-de...,Auditions « Grange Dimière » - « Absolution » 🎼,Extraits du « Dernier jour d’un condamné » de ...,<p>📆 Mardi 10 Décembre<br>🕖 17H30 &amp; 19H00<...,None,None,https://cibul.s3.amazonaws.com/918249ad08fc4c2...,None,https://cibul.s3.amazonaws.com/918249ad08fc4c2...,https://cibul.s3.amazonaws.com/918249ad08fc4c2...,2024-12-03T08:30:29+00:00,"Mardi 10 décembre, 17h30, 19h00",2024-12-10T16:30:00+00:00,2024-12-10T18:00:00+00:00,2024-12-10T18:00:00+00:00,2024-12-10T19:30:00+00:00,"[{""begin"": ""2024-12-10T17:30:00+01:00"", ""end"":...",None,None,1249258,"{'lon': 3.228291, 'lat': 50.17482}",La Grange Dimière Cambrai,"4 Rue Saint-Julien, 59400 Cambrai",None,59122.0,59400.0,Cambrai,Nord,Hauts-de-France,FR,None,None,None,None,None,None,None,None,"{""id"": 1, ""label"": {""fr"": ""Sur place"", ""en"": ""...",None,"{""id"": 1, ""label"": {""fr"": ""Programm\u00e9"", ""e...",NaN,NaN,Agenda du territoire de la Communauté d'agglom...,43736724,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),None,None
2,94058353,popeyes-recrute-pour-une-nouvelle-ouverture-a-...,https://openagenda.com/semaine-des-metiers-du-...,"POPEYES recrute, pour une nouvelle ouverture à...",Dans le cadre de son ouverture à Lille le 23 a...,<p>Dans le cadre de son ouverture à Lille le 2...,None,"[Job dating, La semaine du Tourisme, Recruteme...",None,None,None,None,2025-03-11T08:39:05+00:00,"Lundi 3 mars, 13h30",2025-03-03T12:30:00+00:00,2025-03-03T15:30:00+00:00,2025-03-03T12:30:00+00:00,2025-03-03T15:30:00+00:00,"[{""begin"": ""2025-03-03T13:30:00+01:00"", ""end"":...",None,None,64230015,"{'lon': 3.05968, 'lat': 50.633129}",Lille,59800 Lille,Lille-Centre,59350.0,59800.0,Lille,Nord,Hauts-de-France,FR,None,None,None,None,None,None,None,None,"{""id"": 1, ""label"": {""fr"": ""Sur place"", ""en"": ""...",None,"{""id"": 1, ""label"": {""fr"": ""Programm\u00e9"", ""e...",NaN,NaN,Mes événements France Travail,38495884,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""link"", ""value"": ""https://meseveneme...",None
3,46860549,rejoignez-la-chicoree-job-dating-pour-cuisinie...,https://openagenda.com/semaine-des-metiers-du-...,Rejoignez La Chicorée : Job Dating pour Cuisin...,Participez à notre job dating exclusif organis...,<p>Participez à notre job dating exclusif orga...,None,"[Job dating, 1 jeune 1 solution, La semaine d...",None,None,None,None,2025-03-09T06:45:38+00:00,"Jeudi 6 mars, 14h30",2025-03-06T13:30:00+00:00,2025-03-06T14:00:00+00:00,2025-03-06T13:30:00+00:00,2025-03-06T14:00:00+00:00,"[{""begin"": ""2025-03-06T14:30:00+01:00"", ""end"":...",None,None,26197102,"{'lon': 3.059694, 'lat': 50.633263}",Lille,59800 Lille,Lille-Centre,59350.0,59800.0,Lille,Nord,Hauts-de-France,FR,None,None,None,None,None,None,None,None,"{""id"": 1, ""label"": {""fr"": ""Sur place"", ""en"": ""...",None,"{""id"": 1, ""label"": {""fr"": ""Programm\u00e9"", ""e...",NaN,NaN,Mes événements France Travail,38495884,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),"[{""type"": ""link"", ""value"": ""https://meseveneme...",None
4,40400434,dis-moi-dix-mots-avec-la-pjj-grand-nord-atelie...,https://openagenda.com/dismoidixmots-2025/even...,"Dis-moi dix mots avec la PJJ Grand-Nord, ateli...",Dis-moi Dix mots,<p>Le Labo des histoires Hauts-de-France et Ho...,None,None,https://cdn.openagenda.com/main/26fadd8a008a43...,Luc Melanson,https://cdn.openagenda.com/main/26fadd8a008a43...,https://cdn.openagenda.com/main/26fadd8a008a43...,2025-02-10T09:07:02+00:00,17 - 31 janvier,2025-01-17T09:00:00+00:00,2025-01-17T11:00:00+00:00,2025-01-31T12:30:00+00:00,2025-01-31T14:30:00+00:00,"[{""begin"": ""2025-01-17T10:00:00+01:00"", ""end"":...",None,None,13653731,"{'lon': 2.7771179999999998, 'lat': 50.409867}",CEF de Liévin,62800 Liévin,None,62510.0,62800.0,Liévin,Pas-de-Calais,Hauts-de-France,FR,None,None,None,None,None,None,None,None,"{""id"": 1, ""label"": {""fr"": ""Sur place"", ""en"": ""...",None,"{""id"": 1, ""label"": {""fr"": ""Programm\u00e9"", ""e...",NaN,NaN,Dis-moi Dix mots 2025,5070505,NaN,NaN,NaN,NaN,NaN,NaN,France (Métropole),None,None

<div style="background: #3498db; color: white; padding: 1rem 2rem; border-radius: 5px;">
    <p style="margin: 0;">
        Le dataset contenant un grand nombre de lignes et de colonnes, nous commencerons par sélectionner les variables pertinentes pour le chatbot avant d'analyser le taux de valeurs manquantes.
    </p>
</div>

<div style="background: #27ae60; color: white; padding: 1rem 2rem; border-radius: 5px;">
    <p style="margin: 0;">
    Quelles sont les colonnes disponibles ?    </p>
</div>

In [3]:
missing_df = (
    df.isna()
      .mean()
      .mul(100)
      .round(2)
      .reset_index()
      .rename(columns={"index": "colonne", 0: "valeur manquante"})
)

print(missing_df)

                        colonne  valeur manquante
0                           uid              0.00
1                          slug              0.00
2                  canonicalurl              0.00
3                      title_fr              0.02
4                description_fr              0.02
5            longdescription_fr              3.03
6                 conditions_fr             47.56
7                   keywords_fr             75.91
8                         image             10.20
9                  imagecredits             29.20
10                    thumbnail             10.36
11                originalimage             10.36
12                    updatedat              0.00
13                 daterange_fr              0.00
14              firstdate_begin              0.00
15                firstdate_end              0.00
16               lastdate_begin              0.00
17                 lastdate_end              0.00
18                      timings              0.00
19                accessibility             80.87
20       accessibility_label_fr             80.87
21                 location_uid              0.00
22         location_coordinates              0.52
23                location_name              0.00
24             location_address              0.00
25            location_district             71.91
26               location_insee              5.03
27          location_postalcode              0.90
28                location_city              0.00
29          location_department              0.00
30              location_region              0.00
31         location_countrycode              0.00
32               location_image             68.10
33        location_imagecredits             70.36
34               location_phone             63.42
35             location_website             66.48
36               location_links             85.12
37                location_tags             60.65
38      location_description_fr             66.41
39           location_access_fr             77.74
40               attendancemode              0.00
41             onlineaccesslink             98.54
42                       status              0.00
43                      age_min             90.41
44                      age_max             86.55
45           originagenda_title              0.00
46             originagenda_uid              0.00
47            contributor_email            100.00
48    contributor_contactnumber            100.00
49      contributor_contactname            100.00
50  contributor_contactposition            100.00
51     contributor_organization            100.00
52                     category            100.00
53                   country_fr              0.00
54                 registration             60.46
55                        links             89.30

<div style="background: #3498db; color: white; padding: 1rem 2rem; border-radius: 5px;">
    <p style="margin: 0 0 0.75rem 0; font-weight: 600;">
        Nous avons pas mal de colonnes, mais certaines sont plus importantes que d'autres :
    </p>
    <ul style="margin: 0; padding-left: 1.2rem;">
        <li>title_fr</li>
        <li>description_fr</code></li>
        <li>longdescription_fr</code></li>
        <li>conditions_fr</code></li>
        <li>timings</code></li>
        <li>location_name</code></li>
        <li>location_address</code></li>
        <li>location_insee</code></li>
        <li>location_postalcode</code></li>
        <li>location_city</code></li>
        <li>location_department</code></li>
        <li>location_region</code></li>
        <li>location_countrycode</code></li>
        <li>age_min</code></li>
        <li>age_max</code></li>
        <li>registration</code></li>
    </ul>
</div>

In [4]:
column_keep = [
    "title_fr",
    "description_fr",
    "longdescription_fr",
    "conditions_fr",
    "timings",
    "location_name",
    "location_address",
    "location_insee",
    "location_postalcode",
    "location_city",
    "location_department",
    "location_region",
    "location_countrycode",
    "age_min",
    "age_max",
    "registration",
    "location_phone",          
    "location_website"
]

In [5]:
df = df[column_keep]
df.head()

,title_fr,description_fr,longdescription_fr,conditions_fr,timings,location_name,location_address,location_insee,location_postalcode,location_city,location_department,location_region,location_countrycode,age_min,age_max,registration,location_phone,location_website
0,Comptines et chansons à la bibliothèque,Comptines et chansons avec Jérôme et sa guitare,<p>Comptines et chansons avec Jérôme et sa gui...,Réservation indispensable,"[{""begin"": ""2025-03-29T10:15:00+01:00"", ""end"":...",médiathèque de Moulins,8 allée de la Filature 59 000 Lille,59350.0,59000.0,Lille,Nord,Hauts-de-France,FR,NaN,3.0,"[{""type"": ""phone"", ""value"": ""03 28 55 30 93""}]",03 28 55 30 93,http://bm-lille.fr
1,Auditions « Grange Dimière » - « Absolution » 🎼,Extraits du « Dernier jour d’un condamné » de ...,<p>📆 Mardi 10 Décembre<br>🕖 17H30 &amp; 19H00<...,None,"[{""begin"": ""2024-12-10T17:30:00+01:00"", ""end"":...",La Grange Dimière Cambrai,"4 Rue Saint-Julien, 59400 Cambrai",59122.0,59400.0,Cambrai,Nord,Hauts-de-France,FR,NaN,NaN,None,None,None
2,"POPEYES recrute, pour une nouvelle ouverture à...",Dans le cadre de son ouverture à Lille le 23 a...,<p>Dans le cadre de son ouverture à Lille le 2...,None,"[{""begin"": ""2025-03-03T13:30:00+01:00"", ""end"":...",Lille,59800 Lille,59350.0,59800.0,Lille,Nord,Hauts-de-France,FR,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://meseveneme...",None,None
3,Rejoignez La Chicorée : Job Dating pour Cuisin...,Participez à notre job dating exclusif organis...,<p>Participez à notre job dating exclusif orga...,None,"[{""begin"": ""2025-03-06T14:30:00+01:00"", ""end"":...",Lille,59800 Lille,59350.0,59800.0,Lille,Nord,Hauts-de-France,FR,NaN,NaN,"[{""type"": ""link"", ""value"": ""https://meseveneme...",None,None
4,"Dis-moi dix mots avec la PJJ Grand-Nord, ateli...",Dis-moi Dix mots,<p>Le Labo des histoires Hauts-de-France et Ho...,None,"[{""begin"": ""2025-01-17T10:00:00+01:00"", ""end"":...",CEF de Liévin,62800 Liévin,62510.0,62800.0,Liévin,Pas-de-Calais,Hauts-de-France,FR,NaN,NaN,None,None,None

<div style="background: #2c3e50; 
            color: white; 
            padding: 20px; 
            border-radius: 8px;
            margin: 10px 0;">
    <h1 style="margin: 0; font-size: 24px;">
        Étape 3 : Nettoyage des données
    </h1>
</div>

In [6]:
print(f"Nombre d'événements avant le nettoyage sur les valeurs indispenssable : {len(df)}")

df = df[
    (df['title_fr'].notnull()) & 
    (df['location_address'].notnull()) &
    (df['description_fr'].notnull()) &
    (df['timings'].notnull())
]

print(f"Nombre d'événements après le nettoyage : {len(df)}")

Nombre d'événements avant le nettoyage sur les valeurs indispenssable : 5746
Nombre d'événements après le nettoyage : 5745

In [7]:
# Format Age / location_insee / location_postalcode en int
df['location_insee'] = df['location_insee'].astype('Int64')
df['location_postalcode'] = df['location_postalcode'].astype('Int64')
df['age_min'] = df['age_min'].astype('Int64')
df['age_max'] = df['age_max'].astype('Int64')

df['location_phone'] = df['location_phone'].fillna("pas de numéro de téléphone")
df['location_website'] = df['location_website'].fillna("pas de site")

print(df[['location_insee', 'location_postalcode','age_min', 'age_max', 'location_website', 'location_phone']].head())

   location_insee  location_postalcode  age_min  age_max    location_website  \
0           59350                59000     <NA>        3  http://bm-lille.fr
1           59122                59400     <NA>     <NA>         pas de site
2           59350                59800     <NA>     <NA>         pas de site
3           59350                59800     <NA>     <NA>         pas de site
4           62510                62800     <NA>     <NA>         pas de site

               location_phone
0              03 28 55 30 93
1  pas de numéro de téléphone
2  pas de numéro de téléphone
3  pas de numéro de téléphone
4  pas de numéro de téléphone

In [8]:
df['conditions_fr'] = df['conditions_fr'].fillna("Aucune condition précisée")
df['registration'] = df['registration'].fillna("Pas de lien d'inscription")
print(df[['registration', 'conditions_fr']].head())

                                        registration  \
0     [{"type": "phone", "value": "03 28 55 30 93"}]
1                          Pas de lien d'inscription
2  [{"type": "link", "value": "https://meseveneme...
3  [{"type": "link", "value": "https://meseveneme...
4                          Pas de lien d'inscription

               conditions_fr
0  Réservation indispensable
1  Aucune condition précisée
2  Aucune condition précisée
3  Aucune condition précisée
4  Aucune condition précisée

In [9]:
# Nettoyer l'HTML

def remove_html(text):
    if not text or str(text) == 'nan':
        return ""
        
    text_no_html = BeautifulSoup(text, "html.parser").get_text(separator=" ")
    text_clean = re.sub(r'\s+', ' ', text_no_html)
    return text_clean.strip()

df['longdescription_fr' ] = df['longdescription_fr' ].apply(remove_html)

print(df[['longdescription_fr']].head())

                                  longdescription_fr
0  Comptines et chansons avec Jérôme et sa guitar...
1  📆 Mardi 10 Décembre 🕖 17H30 & 19H00 Professeur...
2  Dans le cadre de son ouverture à Lille le 23 a...
3  Participez à notre job dating exclusif organis...
4  Le Labo des histoires Hauts-de-France et Hors ...

In [10]:
# Nettoyer inscription

def clean_registration(value):
    if not value or str(value) == 'nan':
        return "Entrée libre"
        
    try:
        reg_list = json.loads(value)
        
        infos_contact = []
        
        for item in reg_list:
            type_contact = item.get('type')
            valeur_contact = item.get('value')
            
            if type_contact == 'phone':
                infos_contact.append(f"phone: {valeur_contact}")
            elif type_contact == 'email':
                infos_contact.append(f"email: {valeur_contact}")
            elif type_contact == 'link':
                infos_contact.append(f"link: {valeur_contact}")
            else:
                infos_contact.append(valeur_contact)
        
        if not infos_contact:
            return "Voir description"
            
        return " | ".join(infos_contact)
        
    except Exception:
        return "Voir description"



df['registration'] = df['registration'].apply(clean_registration)

In [11]:
# Nettoyer timing

def clean_timings(value):
    if not value or str(value) == 'nan':
        return "Horaires non précisés"
    
    try:
        timings_list = json.loads(value)
        
        readable_dates = []
        for t in timings_list:
            start = datetime.fromisoformat(t['begin'])
            end = datetime.fromisoformat(t['end'])
            
            date_str = start.strftime("%d/%m/%Y")
            start_hour = start.strftime("%H:%M")
            end_hour = end.strftime("%H:%M")
            
            readable_dates.append(f"Le {date_str} de {start_hour} à {end_hour}")
            
        return " / ".join(readable_dates)
        
    except (json.JSONDecodeError, ValueError, TypeError):
        return "Horaires invalides"
        
df['timings'] = df['timings'].apply(clean_timings)

In [12]:
df.head(10)

,title_fr,description_fr,longdescription_fr,conditions_fr,timings,location_name,location_address,location_insee,location_postalcode,location_city,location_department,location_region,location_countrycode,age_min,age_max,registration,location_phone,location_website
0,Comptines et chansons à la bibliothèque,Comptines et chansons avec Jérôme et sa guitare,Comptines et chansons avec Jérôme et sa guitar...,Réservation indispensable,Le 29/03/2025 de 10:15 à 11:30,médiathèque de Moulins,8 allée de la Filature 59 000 Lille,59350,59000,Lille,Nord,Hauts-de-France,FR,<NA>,3,phone: 03 28 55 30 93,03 28 55 30 93,http://bm-lille.fr
1,Auditions « Grange Dimière » - « Absolution » 🎼,Extraits du « Dernier jour d’un condamné » de ...,📆 Mardi 10 Décembre 🕖 17H30 & 19H00 Professeur...,Aucune condition précisée,Le 10/12/2024 de 17:30 à 19:00 / Le 10/12/2024...,La Grange Dimière Cambrai,"4 Rue Saint-Julien, 59400 Cambrai",59122,59400,Cambrai,Nord,Hauts-de-France,FR,<NA>,<NA>,Voir description,pas de numéro de téléphone,pas de site
2,"POPEYES recrute, pour une nouvelle ouverture à...",Dans le cadre de son ouverture à Lille le 23 a...,Dans le cadre de son ouverture à Lille le 23 a...,Aucune condition précisée,Le 03/03/2025 de 13:30 à 16:30,Lille,59800 Lille,59350,59800,Lille,Nord,Hauts-de-France,FR,<NA>,<NA>,link: https://mesevenementsemploi.francetravai...,pas de numéro de téléphone,pas de site
3,Rejoignez La Chicorée : Job Dating pour Cuisin...,Participez à notre job dating exclusif organis...,Participez à notre job dating exclusif organis...,Aucune condition précisée,Le 06/03/2025 de 14:30 à 15:00,Lille,59800 Lille,59350,59800,Lille,Nord,Hauts-de-France,FR,<NA>,<NA>,link: https://mesevenementsemploi.francetravai...,pas de numéro de téléphone,pas de site
4,"Dis-moi dix mots avec la PJJ Grand-Nord, ateli...",Dis-moi Dix mots,Le Labo des histoires Hauts-de-France et Hors ...,Aucune condition précisée,Le 17/01/2025 de 10:00 à 12:00 / Le 17/01/2025...,CEF de Liévin,62800 Liévin,62510,62800,Liévin,Pas-de-Calais,Hauts-de-France,FR,<NA>,<NA>,Voir description,pas de numéro de téléphone,pas de site
5,REUNION D INFORMATION SECTEUR HCRB (HOTELLERIE...,Le secteur HCRB (Hôtellerie- Café- Restauratio...,Le secteur HCRB (Hôtellerie- Café- Restauratio...,Aucune condition précisée,Le 03/03/2025 de 14:00 à 17:00,Tilloy-lès-Mofflaines,62217 Tilloy-lès-Mofflaines,62817,62217,Tilloy-lès-Mofflaines,Pas-de-Calais,Hauts-de-France,FR,<NA>,<NA>,link: https://mesevenementsemploi.francetravai...,pas de numéro de téléphone,pas de site
6,"Dis-moi dix mots avec la PJJ Grand-Nord, ateli...",Dis-moi Dix mots,Le Labo des histoires Hauts-de-France et Hors ...,Aucune condition précisée,Le 20/05/2025 de 09:00 à 16:00,Les Hortillonnages,Amiens,80021,<NA>,Amiens,Somme,Hauts-de-France,FR,<NA>,<NA>,Voir description,pas de numéro de téléphone,pas de site
7,Conseil communautaire,Les conseillers communautaires des 50 communes...,Retrouvez l'ensemble des délibérations ICI,Entrée libre,Le 18/03/2025 de 18:30 à 20:30,Hôtel communautaire,222 bis rue de Vieux-Berquin,59295,59190,Hazebrouck,Nord,Hauts-de-France,FR,<NA>,<NA>,Voir description,pas de numéro de téléphone,pas de site
8,Popcorn,Un spectacle d'impro de Molière au film catast...,Popcorn est un spectacle de théâtre improvisé ...,Gratuit,Le 25/01/2025 de 19:00 à 20:00,L'Atelier Média,Place de la Gare - 62220 Carvin,62215,62220,Carvin,Pas-de-Calais,Hauts-de-France,FR,<NA>,<NA>,phone: 0321747430 | email: mediaresa@carvin.fr...,03 21 74 74 30,http://www.mediatheques-rcm.fr/carvin
9,"Atelier ""Grandir en s'amusant""",Le Service de Soutien Éducatif Enfants-Parents...,"À partir d'activités créatives et ludiques, ce...",Inscription,Le 18/02/2025 de 10:00 à 11:30,Mairie Oudezeele,"70 Rue de la Forge, 59670 Oudezeele",59453,59670,Oudezeele,Nord,Hauts-de-France,FR,<NA>,<NA>,phone: 03 20 37 60 64,pas de numéro de téléphone,pas de site

<div style="background: #2c3e50; 
            color: white; 
            padding: 20px; 
            border-radius: 8px;
            margin: 10px 0;">
    <h1 style="margin: 0; font-size: 24px;">
        Étape 4 : Exportation des données après nettoyage
    </h1>
</div>

In [13]:
data_list = df.to_dict(orient='records')

with open("outputs/evenements-publics-openagenda-clean.json", 'w', encoding='utf-8') as f: 
    json.dump( data_list, f, ensure_ascii=False,indent=4)

print(f"Fichier nettoyé et sauvegardé dans 'outputs/evenements-publics-openagenda-clean.json'")

Fichier nettoyé et sauvegardé dans 'outputs/evenements-publics-openagenda-clean.json'